TARGET = auth-pwd

CC = gcc
CFLAGS += -D_DEFAULT_SOURCE
LDFLAGS += -lcrypt

SRCS = auth-pwd.c
OBJS = $(SRCS:.c=.o)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) $(OBJS)